language: node_js

node_js:
  - 4.5
  - 6.5

before_install:
  - docker run -d -e ARANGO_NO_AUTH=1 -p 8529:8529 arangodb:3.0.4
  - CONTINUE=1
  - while [ $CONTINUE -eq 1 ]; do sleep 1 && curl -s 127.0.0.1:8529/_api/version && CONTINUE=0; done

services:
  - docker

script:
  - ARANGO_HOST=127.0.0.1 npm test